FROM python:3.11-slim

WORKDIR /app

COPY ./server/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./server .
COPY ./data /data
COPY ./model /model
COPY ./ui /ui

EXPOSE 8000

# CMD ["python", "app.py"]
CMD sleep infinity